# Makefile for building the IDS-by-ML final report (LLNCS / Springer LNCS).
#
# Usage:
#   make            # build main.pdf (runs pdflatex twice to resolve refs)
#   make quick      # build main.pdf with a single pdflatex pass (faster, refs may be stale)
#   make view       # open main.pdf in the default viewer (macOS / Linux)
#   make clean      # remove LaTeX auxiliary files (.aux .log .out .toc ...)
#   make distclean  # clean + remove main.pdf
#
# Requires a TeX Live installation with the following collections:
#   - texlive-latex-base / texlive-latex-recommended / texlive-latex-extra
#   - texlive-fonts-recommended
#   - texlive-pictures (tikz, pgfplots)
#   - texlive-science  (algorithm, algpseudocode)         <-- "collection-mathscience" via tlmgr
#
# The LLNCS class file (llncs.cls) and the splncs04 bibliography style
# (splncs04.bst) are shipped inside this folder, so no extra setup is
# required beyond a working pdflatex binary.

# --- Configurable knobs ---------------------------------------------------
LATEX       ?= pdflatex
LATEXFLAGS  ?= -interaction=nonstopmode -halt-on-error
REPORT_DIR   = report
MAIN         = main
SECTIONS     = 1 2 3 4 5 6
SRC          = $(REPORT_DIR)/$(MAIN).tex \
               $(foreach s,$(SECTIONS),$(wildcard $(REPORT_DIR)/$(s)/*.tex)) \
               $(REPORT_DIR)/llncs.cls $(REPORT_DIR)/splncs04.bst

# --- Default target -------------------------------------------------------
.PHONY: all
all: $(REPORT_DIR)/$(MAIN).pdf

# Two pdflatex passes are needed to resolve \ref / \cite / \label references.
$(REPORT_DIR)/$(MAIN).pdf: $(SRC)
	cd $(REPORT_DIR) && $(LATEX) $(LATEXFLAGS) $(MAIN).tex
	cd $(REPORT_DIR) && $(LATEX) $(LATEXFLAGS) $(MAIN).tex
	@echo ""
	@echo "--> Built $(REPORT_DIR)/$(MAIN).pdf ($$(pdfinfo $(REPORT_DIR)/$(MAIN).pdf 2>/dev/null | awk '/^Pages:/ {print $$2" pages"}'))"

# --- Fast single-pass build (cross-references may be stale) ---------------
.PHONY: quick
quick:
	cd $(REPORT_DIR) && $(LATEX) $(LATEXFLAGS) $(MAIN).tex

# --- View the compiled PDF ------------------------------------------------
.PHONY: view
view: $(REPORT_DIR)/$(MAIN).pdf
	@if command -v open >/dev/null 2>&1; then \
	    open $(REPORT_DIR)/$(MAIN).pdf; \
	elif command -v xdg-open >/dev/null 2>&1; then \
	    xdg-open $(REPORT_DIR)/$(MAIN).pdf; \
	else \
	    echo "No PDF viewer found. Open $(REPORT_DIR)/$(MAIN).pdf manually."; \
	fi

# --- Clean targets --------------------------------------------------------
# Aux extensions generated by pdflatex / biblatex / hyperref / listings.
AUX_EXT = aux log out toc lof lot bbl blg nav snm vrb fls fdb_latexmk synctex.gz

.PHONY: clean
clean:
	@for ext in $(AUX_EXT); do \
	    find $(REPORT_DIR) -type f -name "*.$$ext" -delete; \
	done
	@echo "--> Cleaned LaTeX auxiliary files in $(REPORT_DIR)."

.PHONY: distclean
distclean: clean
	@rm -f $(REPORT_DIR)/$(MAIN).pdf
	@echo "--> Removed $(REPORT_DIR)/$(MAIN).pdf."

# --- Help -----------------------------------------------------------------
.PHONY: help
help:
	@echo "Targets:"
	@echo "  all        build main.pdf (default)"
	@echo "  quick      single-pass build (fast, refs may be stale)"
	@echo "  view       open main.pdf in the default viewer"
	@echo "  clean      remove LaTeX aux files"
	@echo "  distclean  clean + remove main.pdf"
	@echo "  help       this message"
